#!/usr/bin/env python3
"""
IMC Partitioned Scheduling: BFD / FFD / WFD / CU-UDP
with EDF-VD utilization-based schedulability test

Reads task sets generated by imc_taskset_generator.py,
partitions them onto processors using BFD/FFD/WFD,
and reports acceptance ratios.

Usage:
  - Eclipse / IDE: Edit the PARAMETERS section below, then Run.
  - Terminal:      python imc_partitioning.py
"""

import numpy as np
import json
import os
import csv
import time
import glob
from typing import List, Dict, Tuple, Optional


# ╔══════════════════════════════════════════════════════════════╗
# ║                    PARAMETERS (EDIT HERE)                    ║
# ╚══════════════════════════════════════════════════════════════╝

# --- Input / Output ---
INPUT_DIR        = "/Users/jaewoo/data/com/data"    # Directory with generated JSON files
OUTPUT_DIR       = "/Users/jaewoo/data/com"    # Directory for results

# --- Processor configurations ---
PROCESSORS       = [2, 4, 8]                   # Must match generator settings

# --- Algorithms to compare ---
ALGORITHMS       = ["FFD", "BFD", "WFD", "CU-UDP"]  # Partitioning heuristics

# --- Utilization cap range (must match generator) ---
UTIL_CAP_LO_RATIO = 0.45
UTIL_CAP_HI_RATIO = 0.95
# Step = 0.1 * m (same as generator)

# ╔══════════════════════════════════════════════════════════════╗
# ║                  END OF PARAMETERS                           ║
# ╚══════════════════════════════════════════════════════════════╝


# ============================================================
# Processor State
# ============================================================

class Processor:
    """Tracks utilization state for a single processor."""

    def __init__(self):
        self.U_LC_A = 0.0   # U^A_LC = sum u_LO of LC tasks
        self.U_HC_L = 0.0   # U^L_HC = sum u_LO of HC tasks
        self.U_LC_D = 0.0   # U^D_LC = sum u_HI of LC tasks
        self.U_HC_H = 0.0   # U^H_HC = sum u_HI of HC tasks
        self.tasks = []

    @property
    def U_LO(self) -> float:
        """Total LO-mode utilization = U^A_LC + U^L_HC."""
        return self.U_LC_A + self.U_HC_L

    @property
    def U_HI(self) -> float:
        """Total HI-mode utilization = U^D_LC + U^H_HC."""
        return self.U_LC_D + self.U_HC_H

    @property
    def residual_capacity(self) -> float:
        """Residual capacity = 1 - max(U_LO, U_HI)."""
        return 1.0 - max(self.U_LO, self.U_HI)

    @property
    def util_diff(self) -> float:
        """HC utilization difference = U^H_HC - U^L_HC.
        Used by CU-UDP to balance pessimism across processors."""
        return self.U_HC_H - self.U_HC_L

    def try_add(self, task: dict) -> bool:
        """
        Check if adding task keeps this processor schedulable.

        Returns True if schedulable after adding the task.
        Does NOT actually add the task.
        """
        # Compute new utilizations if task were added
        if task["crit"] == "HC":
            new_U_LC_A = self.U_LC_A
            new_U_HC_L = self.U_HC_L + task["u_LO"]
            new_U_LC_D = self.U_LC_D
            new_U_HC_H = self.U_HC_H + task["u_HI"]
        else:  # LC
            new_U_LC_A = self.U_LC_A + task["u_LO"]
            new_U_HC_L = self.U_HC_L
            new_U_LC_D = self.U_LC_D + task["u_HI"]
            new_U_HC_H = self.U_HC_H

        return _is_schedulable(new_U_LC_A, new_U_HC_L, new_U_LC_D, new_U_HC_H)

    def add(self, task: dict):
        """Actually add a task to this processor."""
        if task["crit"] == "HC":
            self.U_HC_L += task["u_LO"]
            self.U_HC_H += task["u_HI"]
        else:
            self.U_LC_A += task["u_LO"]
            self.U_LC_D += task["u_HI"]
        self.tasks.append(task)

    def residual_capacity_after(self, task: dict) -> float:
        """Compute residual capacity if task were added (without adding)."""
        if task["crit"] == "HC":
            new_U_LO = self.U_LO + task["u_LO"]
            new_U_HI = self.U_HI + task["u_HI"]
        else:
            new_U_LO = self.U_LO + task["u_LO"]
            new_U_HI = self.U_HI + task["u_HI"]
        return 1.0 - max(new_U_LO, new_U_HI)


# ============================================================
# Schedulability Test (per processor)
# ============================================================

def _is_schedulable(U_LC_A: float, U_HC_L: float,
                    U_LC_D: float, U_HC_H: float) -> bool:
    """
    Check if a processor with the given utilizations is schedulable
    under EDF-VD (IMC model).

    Implements Theorem 3 from the paper:
      (1) If U^H_HC + U^A_LC <= 1, schedulable by plain EDF.
      (2) Otherwise, check EDF-VD conditions:
          x_min = U^L_HC / (1 - U^A_LC)
          x_max = (1 - (U^H_HC + U^D_LC)) / (U^A_LC - U^D_LC)
          Schedulable if x_min <= x_max.

    Args:
        U_LC_A: sum of u_LO for LC tasks on this processor
        U_HC_L: sum of u_LO for HC tasks on this processor
        U_LC_D: sum of u_HI for LC tasks on this processor
        U_HC_H: sum of u_HI for HC tasks on this processor

    Returns:
        True if schedulable
    """
    # ---- Condition (8): Plain EDF test ----
    # If U^H_HC + U^A_LC <= 1, task set is worst-case reservation
    # schedulable under EDF without deadline scaling.
    # But we also need U^D_LC + U^H_HC <= 1 (HI mode) and
    # U^A_LC + U^L_HC <= 1 (LO mode) for plain EDF.
    U_LO = U_LC_A + U_HC_L
    U_HI = U_LC_D + U_HC_H

    if U_HI <= 1.0 and U_LO <= 1.0:
        # Both modes schedulable by plain EDF
        return True

    # ---- Condition (9): EDF-VD test ----
    # Need: U^A_LC < 1 (otherwise x_min is undefined)
    if U_LC_A >= 1.0:
        return False

    # Need: U^H_HC + U^D_LC < 1
    if U_HC_H + U_LC_D >= 1.0:
        return False

    # Need: U^A_LC > U^D_LC (otherwise x_max denominator <= 0)
    if U_LC_A <= U_LC_D:
        # If U^A_LC == U^D_LC, then lambda=1 for all LC tasks,
        # which means no mode change effect. In this case,
        # we need U_LO <= 1 and U_HI <= 1, already checked above.
        return False

    # x_min from LO-mode condition (Theorem 1):
    #   U^L_HC / x + U^A_LC <= 1
    #   => x >= U^L_HC / (1 - U^A_LC)
    x_min = U_HC_L / (1.0 - U_LC_A)

    # x_max from HI-mode condition (Theorem 2):
    #   x * U^A_LC + (1-x) * U^D_LC + U^H_HC <= 1
    #   => x * (U^A_LC - U^D_LC) <= 1 - U^H_HC - U^D_LC
    #   => x <= (1 - U^H_HC - U^D_LC) / (U^A_LC - U^D_LC)
    x_max = (1.0 - U_HC_H - U_LC_D) / (U_LC_A - U_LC_D)

    # Valid range exists?
    return x_min <= x_max


# ============================================================
# Partitioning Algorithms
# ============================================================

def partition_ffd(tasks: List[dict], num_processors: int) -> bool:
    """
    First Fit Decreasing partitioning.

    Tasks sorted by max(u_LO, u_HI) descending.
    Assign each task to the first processor that can fit it.

    Returns True if all tasks are successfully partitioned.
    """
    sorted_tasks = sorted(tasks, key=lambda t: max(t["u_LO"], t["u_HI"]),
                          reverse=True)
    processors = [Processor() for _ in range(num_processors)]

    for task in sorted_tasks:
        placed = False
        for proc in processors:
            if proc.try_add(task):
                proc.add(task)
                placed = True
                break
        if not placed:
            return False

    return True


def partition_bfd(tasks: List[dict], num_processors: int) -> bool:
    """
    Best Fit Decreasing partitioning.

    Tasks sorted by max(u_LO, u_HI) descending.
    Assign each task to the processor with the SMALLEST residual
    capacity (after adding) that can still fit it.

    Returns True if all tasks are successfully partitioned.
    """
    sorted_tasks = sorted(tasks, key=lambda t: max(t["u_LO"], t["u_HI"]),
                          reverse=True)
    processors = [Processor() for _ in range(num_processors)]

    for task in sorted_tasks:
        best_proc = None
        best_residual = float('inf')

        for proc in processors:
            if proc.try_add(task):
                residual = proc.residual_capacity_after(task)
                if residual < best_residual:
                    best_residual = residual
                    best_proc = proc

        if best_proc is None:
            return False
        best_proc.add(task)

    return True


def partition_wfd(tasks: List[dict], num_processors: int) -> bool:
    """
    Worst Fit Decreasing partitioning.

    Tasks sorted by max(u_LO, u_HI) descending.
    Assign each task to the processor with the LARGEST residual
    capacity (after adding) that can still fit it.

    Returns True if all tasks are successfully partitioned.
    """
    sorted_tasks = sorted(tasks, key=lambda t: max(t["u_LO"], t["u_HI"]),
                          reverse=True)
    processors = [Processor() for _ in range(num_processors)]

    for task in sorted_tasks:
        best_proc = None
        best_residual = -float('inf')

        for proc in processors:
            if proc.try_add(task):
                residual = proc.residual_capacity_after(task)
                if residual > best_residual:
                    best_residual = residual
                    best_proc = proc

        if best_proc is None:
            return False
        best_proc.add(task)

    return True


def partition_cu_udp(tasks: List[dict], num_processors: int) -> bool:
    """
    Criticality-Unaware Utilization Difference based Partitioning (CU-UDP),
    adapted for IMC model.

    Based on: Ramanathan & Easwaran, "Utilization Difference Based
    Partitioned Scheduling of Mixed-Criticality Systems" (2020).

    Key idea: evenly distribute the HC utilization difference
    (U^H_HC - U^L_HC) across all processors to reduce pessimism
    in the EDF-VD schedulability test.

    Algorithm:
      1. All tasks (HC and LC) are sorted together in decreasing order
         of utilization at their respective criticality levels:
         HC tasks by u_HI, LC tasks by u_LO.
      2. For each HC task: worst-fit allocation based on util_diff
         (U^H_HC(phi_k) - U^L_HC(phi_k)), i.e., assign to the
         processor with the SMALLEST util_diff among those that pass
         the schedulability test.
      3. For each LC task: first-fit allocation.

    Returns True if all tasks are successfully partitioned.
    """
    # Step 1: Sort all tasks together, decreasing by criticality-level util
    #   HC tasks keyed by u_HI, LC tasks keyed by u_LO
    def sort_key(t):
        if t["crit"] == "HC":
            return t["u_HI"]
        else:
            return t["u_LO"]

    sorted_tasks = sorted(tasks, key=sort_key, reverse=True)

    processors = [Processor() for _ in range(num_processors)]

    for task in sorted_tasks:
        if task["crit"] == "HC":
            # Worst-fit based on util_diff (smallest difference first)
            # Among schedulable processors, pick the one with smallest util_diff
            candidates = []
            for proc in processors:
                if proc.try_add(task):
                    candidates.append(proc)

            if not candidates:
                return False

            # Pick processor with smallest util_diff
            best_proc = min(candidates, key=lambda p: p.util_diff)
            best_proc.add(task)
        else:
            # LC task: first-fit
            placed = False
            for proc in processors:
                if proc.try_add(task):
                    proc.add(task)
                    placed = True
                    break
            if not placed:
                return False

    return True


PARTITION_FUNCS = {
    "FFD": partition_ffd,
    "BFD": partition_bfd,
    "WFD": partition_wfd,
    "CU-UDP": partition_cu_udp,
}


# ============================================================
# Data Loading
# ============================================================

def load_workloads(input_dir: str, m: int, util_cap: float) -> Optional[List]:
    """
    Load workloads from a JSON file.

    Args:
        input_dir: directory containing JSON files
        m:         number of processors
        util_cap:  utilization cap value

    Returns:
        list of workload dicts, or None if file not found
    """
    filename = f"imc_m{m}_cap{util_cap:.2f}.json"
    filepath = os.path.join(input_dir, filename)

    if not os.path.exists(filepath):
        print(f"  WARNING: File not found: {filepath}")
        return None

    with open(filepath, 'r') as f:
        data = json.load(f)

    return data["workloads"]


# ============================================================
# Experiment Runner
# ============================================================

def run_experiments() -> Dict:
    """
    Run all partitioning experiments.

    Returns:
        results dict: {m: {util_cap: {algorithm: acceptance_ratio}}}
    """
    all_results = {}

    for m in PROCESSORS:
        print(f"\n{'=' * 60}")
        print(f"Processing m = {m} processors")
        print(f"{'=' * 60}")

        step = 0.1 * m
        cap_lo = UTIL_CAP_LO_RATIO * m
        cap_hi = UTIL_CAP_HI_RATIO * m
        util_caps = np.arange(cap_lo, cap_hi + step * 0.01, step)
        util_caps = np.round(util_caps, 2)

        m_results = {}

        # Print header
        header = f"  {'util_cap':>10}"
        for alg in ALGORITHMS:
            header += f"  {alg:>10}"
        header += f"  {'n_sets':>8}  {'time':>8}"
        print(header)
        print("  " + "-" * (len(header) - 2))

        for cap in util_caps:
            cap = float(cap)
            workloads = load_workloads(INPUT_DIR, m, cap)

            if workloads is None:
                continue

            cap_results = {}
            t_start = time.time()

            for alg_name in ALGORITHMS:
                partition_func = PARTITION_FUNCS[alg_name]
                n_accepted = 0

                for wl in workloads:
                    tasks = wl["tasks"]
                    if partition_func(tasks, m):
                        n_accepted += 1

                acceptance_ratio = n_accepted / len(workloads)
                cap_results[alg_name] = acceptance_ratio

            t_elapsed = time.time() - t_start

            # Print row
            row = f"  {cap:>10.2f}"
            for alg in ALGORITHMS:
                row += f"  {cap_results[alg]:>10.4f}"
            row += f"  {len(workloads):>8d}  {t_elapsed:>7.2f}s"
            print(row)

            m_results[cap] = cap_results

        all_results[m] = m_results

    return all_results


# ============================================================
# Export Results
# ============================================================

def export_results(all_results: Dict):
    """Export acceptance ratio results to CSV."""
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    filepath = os.path.join(OUTPUT_DIR, "partitioning_results.csv")

    with open(filepath, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(["num_processors", "util_cap"] + ALGORITHMS)

        for m in sorted(all_results.keys()):
            for cap in sorted(all_results[m].keys()):
                row = [m, f"{cap:.2f}"]
                for alg in ALGORITHMS:
                    row.append(f"{all_results[m][cap][alg]:.4f}")
                writer.writerow(row)

    print(f"\nResults saved: {filepath}")


# ============================================================
# Main
# ============================================================

def main():
    print("=" * 60)
    print("IMC Partitioned Scheduling Experiment")
    print("=" * 60)
    print(f"Input directory:  {INPUT_DIR}")
    print(f"Output directory: {OUTPUT_DIR}")
    print(f"Processors:       {PROCESSORS}")
    print(f"Algorithms:       {ALGORITHMS}")
    print(f"Util cap ratio:   [{UTIL_CAP_LO_RATIO}, {UTIL_CAP_HI_RATIO}]")
    print(f"Util cap step:    0.1 × m")

    all_results = run_experiments()

    export_results(all_results)

    print(f"\n{'=' * 60}")
    print("All done!")
    print(f"{'=' * 60}")


if __name__ == "__main__":
    main()