'''
Created on 2026. 5. 2.

@author: jaewoo
'''
#!/usr/bin/env python3
"""
IMC Partitioned Scheduling: FFD / BFD / WFD / new_FF
with EDF-VD utilization-based schedulability test

Reads task sets generated by imc_taskset_generator.py,
partitions them onto processors using FFD/BFD/WFD/new_FF,
and reports acceptance ratios.

Usage:
  - Eclipse / IDE: Edit the PARAMETERS section below, then Run.
  - Terminal:      python imc_partitioning.py
"""

import numpy as np
import json
import os
import csv
import time
import glob
from typing import List, Dict, Tuple, Optional


# ╔══════════════════════════════════════════════════════════════╗
# ║                    PARAMETERS (EDIT HERE)                    ║
# ╚══════════════════════════════════════════════════════════════╝

# --- Input / Output ---
INPUT_DIR        = "/Users/jaewoo/data/com/data"    # Directory with generated JSON files
OUTPUT_DIR       = "/Users/jaewoo/data/com"    # Directory for results

# --- Processor configurations ---
PROCESSORS       = [2, 4, 8]                   # Must match generator settings

# --- Algorithms to compare ---
ALGORITHMS       = ["FFD", "BFD", "WFD", "new_FF"]  # Partitioning heuristics

# --- Utilization cap range (must match generator) ---
UTIL_CAP_LO_RATIO = 0.45
UTIL_CAP_HI_RATIO = 0.95
# Step = 0.1 * m (same as generator)

# ╔══════════════════════════════════════════════════════════════╗
# ║                  END OF PARAMETERS                           ║
# ╚══════════════════════════════════════════════════════════════╝


# ============================================================
# Schedulability Tests
# ============================================================

def compute_x_min(U_LC_A: float, U_HC_L: float) -> Optional[float]:
    """
    Compute x_min from the LO-mode EDF-VD condition.

      U^L_HC / x + U^A_LC <= 1
      => x >= U^L_HC / (1 - U^A_LC)

    x must be in (0, 1]. Returns x_min, or None if infeasible.
    """
    if U_LC_A >= 1.0:
        return None
    x_min = U_HC_L / (1.0 - U_LC_A)
    if x_min > 1.0:
        return None
    return x_min


def compute_x_max(U_LC_A: float, U_LC_D: float,
                  U_HC_H: float) -> Optional[float]:
    """
    Compute x_max from the original HI-mode EDF-VD condition.

      x * U^A_LC + (1 - x) * U^D_LC + U^H_HC <= 1
      => x <= (1 - U^H_HC - U^D_LC) / (U^A_LC - U^D_LC)

    x must be in (0, 1]. Returns x_max, or None if infeasible.
    """
    denom = U_LC_A - U_LC_D
    if denom <= 0.0:
        return None
    numer = 1.0 - U_HC_H - U_LC_D
    if numer <= 0.0:
        return None
    x_max = numer / denom
    if x_max > 1.0:
        x_max = 1.0
    return x_max


def is_schedulable_original(U_LC_A: float, U_HC_L: float,
                            U_LC_D: float, U_HC_H: float,
                            hc_tasks: list, lc_tasks: list) -> bool:
    """
    Original schedulability test.
    x = x_min, then check HI-mode: x*U^A_LC + (1-x)*U^D_LC + U^H_HC <= 1.
    """
    U_LO = U_LC_A + U_HC_L
    U_HI = U_LC_D + U_HC_H

    if U_LO <= 1.0 and U_HI <= 1.0:
        return True

    x = compute_x_min(U_LC_A, U_HC_L)
    if x is None:
        return False

    hi_util = x * U_LC_A + (1.0 - x) * U_LC_D + U_HC_H
    return hi_util <= 1.0


def is_schedulable_new(U_LC_A: float, U_HC_L: float,
                       U_LC_D: float, U_HC_H: float,
                       hc_tasks: list, lc_tasks: list) -> bool:
    """
    New schedulability test with HI-only concept.

    1) Compute x = x_max from HI-mode condition:
         x_max = (1 - U^H_HC - U^D_LC) / (U^A_LC - U^D_LC)

    2) Among HC tasks, those with u^L_i / x >= u^H_i are "HI-only":
       they run in HI-mode from the start.

    3) LO-mode check:
         sum_{HI-only HC} u^H_i + sum_{non-HI-only HC} u^L_i / x + U^A_LC <= 1
    """
    U_LO = U_LC_A + U_HC_L
    U_HI = U_LC_D + U_HC_H

    if U_LO <= 1.0 and U_HI <= 1.0:
        return True

    x = compute_x_max(U_LC_A, U_LC_D, U_HC_H)
    if x is None:
        return False

    # Classify HC tasks and compute LO-mode sum
    lo_sum = U_LC_A
    for (u_l, u_h) in hc_tasks:
        if u_l / x >= u_h:
            # HI-only: contribute u^H_i
            lo_sum += u_h
        else:
            # Normal: contribute u^L_i / x
            lo_sum += u_l / x

    return lo_sum <= 1.0


# ============================================================
# Processor State
# ============================================================

class Processor:
    """
    Tracks utilization state for a single processor.

    Stores per-task utilization pairs for both HC and LC tasks.
    """

    def __init__(self, sched_func=is_schedulable_original):
        self.U_LC_A = 0.0    # U^A_LC = sum u_LO of LC tasks
        self.U_HC_L = 0.0    # U^L_HC = sum u_LO of HC tasks
        self.U_LC_D = 0.0    # U^D_LC = sum u_HI of LC tasks
        self.U_HC_H = 0.0    # U^H_HC = sum u_HI of HC tasks
        self.hc_tasks = []   # list of (u_LO, u_HI) per HC task
        self.lc_tasks = []   # list of (u_LO, u_HI) per LC task
        self.tasks = []
        self._sched_func = sched_func

    @property
    def U_LO(self) -> float:
        return self.U_LC_A + self.U_HC_L

    @property
    def U_HI(self) -> float:
        return self.U_LC_D + self.U_HC_H

    def try_add(self, task: dict) -> bool:
        """Check if adding task keeps this processor schedulable."""
        if task["crit"] == "HC":
            new_U_LC_A = self.U_LC_A
            new_U_HC_L = self.U_HC_L + task["u_LO"]
            new_U_LC_D = self.U_LC_D
            new_U_HC_H = self.U_HC_H + task["u_HI"]
            new_hc = self.hc_tasks + [(task["u_LO"], task["u_HI"])]
            new_lc = self.lc_tasks
        else:
            new_U_LC_A = self.U_LC_A + task["u_LO"]
            new_U_HC_L = self.U_HC_L
            new_U_LC_D = self.U_LC_D + task["u_HI"]
            new_U_HC_H = self.U_HC_H
            new_hc = self.hc_tasks
            new_lc = self.lc_tasks + [(task["u_LO"], task["u_HI"])]

        return self._sched_func(new_U_LC_A, new_U_HC_L,
                                new_U_LC_D, new_U_HC_H,
                                new_hc, new_lc)

    def add(self, task: dict):
        """Actually add a task to this processor."""
        if task["crit"] == "HC":
            self.U_HC_L += task["u_LO"]
            self.U_HC_H += task["u_HI"]
            self.hc_tasks.append((task["u_LO"], task["u_HI"]))
        else:
            self.U_LC_A += task["u_LO"]
            self.U_LC_D += task["u_HI"]
            self.lc_tasks.append((task["u_LO"], task["u_HI"]))
        self.tasks.append(task)

    def residual_capacity_after(self, task: dict) -> float:
        """Compute residual capacity if task were added (without adding)."""
        new_U_LO = self.U_LO + task["u_LO"]
        new_U_HI = self.U_HI + task["u_HI"]
        return 1.0 - max(new_U_LO, new_U_HI)


# ============================================================
# Partitioning Algorithms
# ============================================================

def _partition(tasks: List[dict], num_processors: int,
               strategy: str, sched_func) -> bool:
    """
    Generic decreasing partitioning.

    Args:
        tasks:           list of task dicts
        num_processors:  number of processors
        strategy:        "FF" (first fit), "BF" (best fit), or "WF" (worst fit)
        sched_func:      schedulability test function for the Processor

    Returns True if all tasks are successfully partitioned.
    """
    sorted_tasks = sorted(tasks, key=lambda t: max(t["u_LO"], t["u_HI"]),
                          reverse=True)
    processors = [Processor(sched_func) for _ in range(num_processors)]

    for task in sorted_tasks:
        if strategy == "FF":
            placed = False
            for proc in processors:
                if proc.try_add(task):
                    proc.add(task)
                    placed = True
                    break
            if not placed:
                return False

        elif strategy == "BF":
            best_proc = None
            best_residual = float('inf')
            for proc in processors:
                if proc.try_add(task):
                    r = proc.residual_capacity_after(task)
                    if r < best_residual:
                        best_residual = r
                        best_proc = proc
            if best_proc is None:
                return False
            best_proc.add(task)

        else:  # WF
            best_proc = None
            best_residual = -float('inf')
            for proc in processors:
                if proc.try_add(task):
                    r = proc.residual_capacity_after(task)
                    if r > best_residual:
                        best_residual = r
                        best_proc = proc
            if best_proc is None:
                return False
            best_proc.add(task)

    return True


def partition_ffd(tasks, m):
    return _partition(tasks, m, "FF", is_schedulable_original)

def partition_bfd(tasks, m):
    return _partition(tasks, m, "BF", is_schedulable_original)

def partition_wfd(tasks, m):
    return _partition(tasks, m, "WF", is_schedulable_original)

def partition_new_ff(tasks, m):
    return _partition(tasks, m, "FF", is_schedulable_new)


PARTITION_FUNCS = {
    "FFD":    partition_ffd,
    "BFD":    partition_bfd,
    "WFD":    partition_wfd,
    "new_FF": partition_new_ff,
}


# ============================================================
# Data Loading
# ============================================================

def load_workloads(input_dir: str, m: int, util_cap: float) -> Optional[List]:
    """
    Load workloads from a JSON file.

    Args:
        input_dir: directory containing JSON files
        m:         number of processors
        util_cap:  utilization cap value

    Returns:
        list of workload dicts, or None if file not found
    """
    filename = f"imc_m{m}_cap{util_cap:.2f}.json"
    filepath = os.path.join(input_dir, filename)

    if not os.path.exists(filepath):
        print(f"  WARNING: File not found: {filepath}")
        return None

    with open(filepath, 'r') as f:
        data = json.load(f)

    return data["workloads"]


# ============================================================
# Experiment Runner
# ============================================================

def run_experiments() -> Dict:
    """
    Run all partitioning experiments.

    Returns:
        results dict: {m: {util_cap: {algorithm: acceptance_ratio}}}
    """
    all_results = {}

    for m in PROCESSORS:
        print(f"\n{'=' * 60}")
        print(f"Processing m = {m} processors")
        print(f"{'=' * 60}")

        step = 0.1 * m
        cap_lo = UTIL_CAP_LO_RATIO * m
        cap_hi = UTIL_CAP_HI_RATIO * m
        util_caps = np.arange(cap_lo, cap_hi + step * 0.01, step)
        util_caps = np.round(util_caps, 2)

        m_results = {}

        # Print header
        header = f"  {'util_cap':>10}"
        for alg in ALGORITHMS:
            header += f"  {alg:>10}"
        header += f"  {'n_sets':>8}  {'time':>8}"
        print(header)
        print("  " + "-" * (len(header) - 2))

        for cap in util_caps:
            cap = float(cap)
            workloads = load_workloads(INPUT_DIR, m, cap)

            if workloads is None:
                continue

            cap_results = {}
            t_start = time.time()

            for alg_name in ALGORITHMS:
                partition_func = PARTITION_FUNCS[alg_name]
                n_accepted = 0

                for wl in workloads:
                    tasks = wl["tasks"]
                    if partition_func(tasks, m):
                        n_accepted += 1

                acceptance_ratio = n_accepted / len(workloads)
                cap_results[alg_name] = acceptance_ratio

            t_elapsed = time.time() - t_start

            # Print row
            row = f"  {cap:>10.2f}"
            for alg in ALGORITHMS:
                row += f"  {cap_results[alg]:>10.4f}"
            row += f"  {len(workloads):>8d}  {t_elapsed:>7.2f}s"
            print(row)

            m_results[cap] = cap_results

        all_results[m] = m_results

    return all_results


# ============================================================
# Export Results
# ============================================================

def export_results(all_results: Dict):
    """Export acceptance ratio results to CSV."""
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    filepath = os.path.join(OUTPUT_DIR, "partitioning_results.csv")

    with open(filepath, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(["num_processors", "util_cap"] + ALGORITHMS)

        for m in sorted(all_results.keys()):
            for cap in sorted(all_results[m].keys()):
                row = [m, f"{cap:.2f}"]
                for alg in ALGORITHMS:
                    row.append(f"{all_results[m][cap][alg]:.4f}")
                writer.writerow(row)

    print(f"\nResults saved: {filepath}")


# ============================================================
# Main
# ============================================================

def main():
    print("=" * 60)
    print("IMC Partitioned Scheduling Experiment")
    print("=" * 60)
    print(f"Input directory:  {INPUT_DIR}")
    print(f"Output directory: {OUTPUT_DIR}")
    print(f"Processors:       {PROCESSORS}")
    print(f"Algorithms:       {ALGORITHMS}")
    print(f"Util cap ratio:   [{UTIL_CAP_LO_RATIO}, {UTIL_CAP_HI_RATIO}]")
    print(f"Util cap step:    0.1 × m")

    all_results = run_experiments()

    export_results(all_results)

    print(f"\n{'=' * 60}")
    print("All done!")
    print(f"{'=' * 60}")


if __name__ == "__main__":
    main()